name = "nano"
version = "9.2"
release = 1

description = "GNU Nano text editor"
homepage = "https://www.nano-editor.org"
license = "GPL-3.0-or-later"

source = "https://www.nano-editor.org/dist/v9/nano-9.2.tar.xz"
sha256 = "05ecb99247b782e8a5b3a25ed4101dd034b0236902f7449bc9795b717642f7e9"

architectures = ["x86_64"]

depends = [
    "ncurses"
]

build_depends = [
    "gcc",
    "make"
]

[build]
system = "autotools"

configure = [
    "--prefix=/usr"
]
