name = "nano"
version = "8.7"
release = 1

description = "GNU Nano text editor"
homepage = "https://www.nano-editor.org"
license = "GPL-3.0-or-later"

source = "https://www.nano-editor.org/dist/v8/nano-8.7.tar.xz"
sha256 = "afd287aa672c48b8e1a93fdb6c6588453d527510d966822b687f2835f0d986e9"

architectures = ["x86_64"]

depends = [
    "ncurses"
]

build_depends = [
    "gcc",
    "make"
]

[build]
system = "autotools"

configure = [
    "--prefix=/usr"
]
