name = "ncurses"
version = "6.6"
release = 1

description = "Terminal handling library for text-based user interfaces"
homepage = "https://invisible-island.net/ncurses/"
license = "X11"

source = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.6.tar.gz"
sha256 = "355b4cbbed880b0381a04c46617b7656e362585d52e9cf84a67e2009b749ff11"

architectures = ["x86_64"]

depends = []

build_depends = [
    "gcc",
    "make"
]

[build]
system = "autotools"

configure = [
    "--prefix=/usr"
]
